# سكريبت استيراد 568 مسلسل باستخدام curl

# قائمة المسلسلات الـ 568
$titles = @(
    "I Am Not Okay with This"
    "Marco Polo"
    "Little House on the Prairie"
    "Salcedo, Leather, and Boogaloo"
    "I'm Not Afraid"
    "Worst Neighbor Ever"
    "Oasis"
    "I Will Find You"
    "The Polygamist"
    "The Haunting of Hill House"
    "Cable Girls"
    "The Witness"
    "Michael Jackson: The Verdict"
    "My Two Cents"
    "Mating Season"
    "The Boroughs"
    "Carizzma"
    "Berlin and the Lady with an Ermine"
    "Between Father and Son"
    "Master of None"
    "The Chestnut Man"
    "Legends"
    "Man on Fire"
    "Should I Marry a Murderer"
    "Flunked"
    "Stranger Things: Tales from '85"
    "Santita"
    "Unchosen"
    "Someone Has to Know"
    "Beef"
    "The Ranch"
    "Bandi"
    "Big Mistakes"
    "Trust Me: The False Prophet"
    "The Predator of Seville"
    "Jo Nesbo's Detective Hole"
    "Something Very Bad Is Going to Happen"
    "Homicide"
    "Radioactive Emergency"
    "Arrested Development"
    "That Night"
    "Dynasty: The Murdochs"
    "The Dinosaurs"
    "Vladimir"
    "A Friend, A Murderer"
    "Crap Happens"
    "Strip Law"
    "Being Gordon Ramsay"
    "How to Get to Heaven from Belfast"
    "Lead Children"
    "Motorvalley"
    "Salvador"
    "Unfamiliar"
    "Cash Queens"
    "Free Bert"
    "Finding Her Edge"
    "Agatha Christie's Seven Dials"
    "His & Hers"
    "Land of Sin"
    "Time Flies"
    "Run Away"
    "Love from 9 to 5"
    "City of Shadows"
    "Home for Christmas"
    "Man vs Baby"
    "Sicilia Express"
    "The Abandons"
    "The Crystal Cuckoo"
    "How To Win The Lottery"
    "The Beast in Me"
    "Mrs Playmen"
    "The Bad Guys: Breaking In"
    "Death by Lightning"
    "Just Alice"
    "Heweliusz"
    "Bad Influencer"
    "Amsterdam Empire"
    "Son of a Donkey"
    "Rulers of Fortune"
    "The Asset"
    "The Monster of Florence"
    "Turn of the Tide"
    "No One Saw Us Leave"
    "Splinter Cell: Deathwatch"
    "Boots"
    "Néro the Assassin"
    "The New Force"
    "Old Dog, New Tricks"
    "Dudes"
    "Riv4li"
    "Wayward"
    "House of Guinness"
    "La Huesped"
    "Billionaires' Bunker"
    "Haunted Hotel"
    "Black Rabbit"
    "Maledictions"
    "Diary of a Ditched Girl"
    "Love Con Revenge"
    "Two Graves"
    "Hostage"
    "Rivers of Fate"
    "In the Mud"
    "Young Millionaires"
    "Marked"
    "Leanne"
    "Unspeakable Sins"
    "Superstar"
    "Delirium"
    "Untamed"
    "Community Squad"
    "Too Much"
    "Under a Dark Sun"
    "The Gringo Hunters"
    "Olympo"
    "The Waterfront"
    "Cocaine Air: Smugglers at 30,000 Ft"
    "Aniela"
    "The Survivors"
    "Barracuda Queens"
    "Sara: Woman in the Shadows"
    "F1: The Academy"
    "Cold Case: The Tylenol Murders"
    "Dept. Q"
    "She the People"
    "Sirens"
    "Real Men"
    "Porni"
    "Rotten Legacy"
    "Football Parents"
    "Secrets We Keep"
    "Bet"
    "Snakes and Ladders"
    "Bad Thoughts"
    "Bad Boy"
    "Unseen"
    "The Four Seasons"
    "The Eternaut"
    "Turning Point: The Vietnam War"
    "Ransom Canyon"
    "Project UFO"
    "The Diamond Heist"
    "The Glass Dome"
    "The Gardener"
    "Bad Influence: The Dark Side of Kidfluencing"
    "How to Sell Drugs Online Fast"
    "Pulse"
    "Gone Girls: The Long Island Serial Killer"
    "The Lady's Companion"
    "Gold & Greed: The Hunt for Fenn's Treasure"
    "From Rock Star to Killer"
    "Caught"
    "The Residence"
    "Woman of the Dead"
    "Adolescence"
    "Welcome to the Family"
    "The Leopard"
    "Medusa"
    "Just One Look"
    "Tuiskoms"
    "Roosters"
    "Toxic Town"
    "Running Point"
    "Zero Day"
    "My Family"
    "The Are Murders"
    "Cassandra"
    "Apple Cider Vinegar"
    "Prison Cell 211"
    "American Manhunt: O.J. Simpson"
    "The Hooligan"
    "Shafted"
    "XO, Kitty"
    "Public Disorder"
    "American Primeval"
    "North of North"
    "Hound's Hill"
    "Subteran"
    "The Breakthrough"
    "Missing You"
    "1992"
    "No Good Deed"
    "La Palma"
    "The Kings of Tupelo: A Southern Crime Saga"
    "One Hundred Years of Solitude"
    "Black Doves"
    "Churchill at War"
    "Senna"
    "The Madness"
    "The Helicopter Heist"
    "A Man on the Inside"
    "Adoration"
    "Sisters' Feud"
    "The Mothers of Penguins"
    "The Cage"
    "Bank Under Siege"
    "Countdown: Paul vs Tyson"
    "Children of the Church Steps"
    "Murder Mindfully"
    "The Manhattan Alien Abduction"
    "The Law According to Lidia Poet"
    "Go Ahead, Brother"
    "The Last Night at Tremore Beach"
    "Beauty in Black"
    "Territory"
    "This Is the Zodiac Speaking"
    "Ancient Apocalypse"
    "The Secret of the River"
    "Starting 5"
    "Deceitful Love"
    "Nobody Wants This"
    "We Were Kings"
    "Mr. McMahon"
    "Monster"
    "Envidiosa"
    "Billionaire Island"
    "Jack Whitehall: Fatherhood with My Father"
    "The Perfect Couple"
    "Caught in the Web: The Murders Behind Zona Divas"
    "Outlast"
    "The King's Affection"
    "Breathless"
    "Kaos"
    "Represent"
    "Baby Fever"
    "The Accident"
    "Wyatt Earp and the Cowboy War"
    "Worst Ex Ever"
    "Unstable"
    "The Decameron"
    "Master of the House"
    "Snowpiercer"
    "The Green Glove Gang"
    "Eva Lasting"
    "Desperate Lies"
    "The Man with 1000 Kids"
    "That '90s Show"
    "Supacell"
    "Gangs of Galicia"
    "America's Sweethearts"
    "Joko Anwar's Nightmares and Daydreams"
    "Hitler and the Nazis: Evil on Trial"
    "Raising Voices"
    "Geek Girl"
    "Eric"
    "Dancing for the Devil: The 7M TikTok Cult"
    "The Life You Wanted"
    "Tires"
    "Toughest Forces on Earth"
    "Maestro"
    "Ashley Madison: Sex, Lies & Scandal"
    "Bodkin"
    "A Man in Full"
    "Fiasco"
    "The Asunta Case"
    "Dead Boy Detectives"
    "Greenleaf"
    "Deliver Me"
    "Brigands: The Quest for Gold"
    "Our Living World"
    "Midsummer Night"
    "Heartbreak High"
    "Baby Reindeer"
    "Anthracite"
    "The Hijacking of Flight 601"
    "Ripley"
    "Crooks"
    "Files of the Unexplained"
    "Crime Scene Berlin: Nightlife Killer"
    "Ronja the Robber's Daughter"
    "3 Body Problem"
    "Iron Reign"
    "Bandidos"
    "Turning Point: The Bomb and the Cold War"
    "The Gentlemen"
    "The Signal"
    "The Program: Cons, Cults, and Kidnapping"
    "Furies"
    "The Vince Staples Show"
    "Good Morning, Verônica"
    "Alpha Males"
    "One Day"
    "Luz: The Light of the Heart"
    "Baby Bandito"
    "Alexander the Great"
    "Griselda"
    "American Nightmare"
    "End of the Line"
    "Detective Forst"
    "Champion"
    "Boy Swallows Universe"
    "The Brothers Sun"
    "Fool Me Once"
    "Captains of the World"
    "Babylon Berlin"
    "The Letdown"
    "Berlin"
    "The Manny"
    "What/If"
    "True Story"
    "Tiny Pretty Things"
    "Tidelands"
    "The Hookup Plan"
    "The Bonfire of Destiny"
    "Snabba Cash"
    "Seven Seconds"
    "Lovesick"
    "The Bastard Son & The Devil Himself"
    "Gypsy"
    "Grand Army"
    "Fate: The Winx Saga"
    "Echoes"
    "Cindy la Regia: The High School Years"
    "Greenhouse Academy"
    "Red Rose"
    "Dogs of Berlin"
    "Dirty John"
    "Dirk Gently's Holistic Detective Agency"
    "Black Summer"
    "Better Than Us"
    "Anatomy of a Scandal"
    "The Snow Girl"
    "The New Legends of Monkey"
    "The Longest Night"
    "Resident Evil"
    "Blood & Water"
    "Biohackers"
    "Yoh! Christmas"
    "If I Were Luísa Sonza"
    "1670"
    "Under Pressure: The U.S. Women's World Cup Team"
    "Wu Assassins"
    "Women at War"
    "The Serpent"
    "The Nurse"
    "The Neighbor"
    "The Mist"
    "The Midnight Club"
    "Ratched"
    "One Day at a Time"
    "Kleo"
    "World War II: From the Frontlines"
    "My Life with the Walter Boys"
    "Happy"
    "Godless"
    "GLOW"
    "From Scratch"
    "Friends from College"
    "First Kill"
    "Dracula"
    "I Hate Christmas"
    "High Tides"
    "Blood Coast"
    "When They See Us"
    "V-Wars"
    "Unorthodox"
    "Undercover"
    "The Witcher: Blood Origin"
    "Raising Dion"
    "On My Block"
    "Mr. Iglesias"
    "Obliterated"
    "Bad Surgeon: Love Under the Knife"
    "Marcella"
    "Keep Breathing"
    "Kaleidoscope"
    "Control Z"
    "Another Life"
    "Alias Grace"
    "3%"
    "A Series of Unfortunate Events"
    "A Nearly Normal Family"
    "The Spy"
    "The Society"
    "The Order"
    "The OA"
    "The Forest"
    "The Empress"
    "The Alienist"
    "The 7 Lives of Lea"
    "Sweet Tooth"
    "Suburra: Blood on Rome"
    "Space Force"
    "Squid Game: The Challenge"
    "Russian Doll"
    "Nothing to See Here"
    "Holy Family"
    "High Seas"
    "Grace and Frankie"
    "Glitch"
    "Ganglands"
    "Derry Girls"
    "Collateral"
    "Barbarians"
    "Feedback"
    "Warrior Nun"
    "The Inmate"
    "Suburræterna"
    "How to Become a Mob Boss"
    "Criminal Code"
    "Sky Rojo"
    "Orange Is the New Black"
    "Lost in Space"
    "Clickbait"
    "Baby"
    "The Billionaire, the Butler & the Boyfriend"
    "Robbie Williams"
    "Escaping Twin Flames"
    "Atypical"
    "Altered Carbon"
    "Workin' Moms"
    "Pretty Smart"
    "Ferry: The Series"
    "All the Light We Cannot See"
    "Till Murder Do Us Part: Soering vs. Haysom"
    "Mysteries of the Faith"
    "Tore"
    "Life on Our Planet"
    "Absolute Beginners"
    "Get Gotti"
    "Wrong Side of the Tracks"
    "Treason"
    "Chilling Adventures of Sabrina"
    "Surviving Paradise"
    "Neon"
    "Bodies"
    "Travelers"
    "The Umbrella Academy"
    "The Marked Heart"
    "Shadowhunters"
    "Inside Man"
    "In from the Cold"
    "I Woke Up a Vampire"
    "Gilmore Girls: A Year in the Life"
    "El Chapo"
    "The Fall of the House of Usher"
    "Sex/Life"
    "Pacto De Silencio"
    "Big Vape: The Rise and Fall of Juul"
    "House of Cards"
    "Everything Now"
    "Beckham"
    "Who Killed Sara"
    "Unbelievable"
    "The Watcher"
    "The Rain"
    "The Innocent"
    "Fake Profile"
    "Diary of a Gigolo"
    "The Diplomat"
    "Pieces of Her"
    "Norsemen"
    "Muted"
    "Behind Her Eyes"
    "You"
    "Welcome to Eden"
    "The Queen's Gambit"
    "The Mess You Leave Behind"
    "Encounters"
    "Shadow and Bone"
    "Good Girls"
    "Dynasty"
    "Bloodline"
    "The Crown"
    "Rita"
    "Perfume"
    "Mindhunter"
    "Maid"
    "Vis a Vis: El Oasis"
    "Vis a vis"
    "Fuller House"
    "Emily in Paris"
    "Cobra Kai"
    "Anne with an E"
    "Ginny & Georgia"
    "Firefly Lane"
    "Cursed"
    "Frontier"
    "Dark Desire"
    "Valeria"
    "Sense8"
    "I Am Georgina"
    "After Life"
    "Locke & Key"
    "Insatiable"
    "Dead to Me"
    "Bridgerton"
    "Wanted"
    "Unauthorized Living"
    "Hit & Run"
    "Florida Man"
    "Bodyguard"
    "Triptych"
    "The Recruit"
    "Sky High"
    "Miseducation"
    "Outer Banks"
    "Narcos: Mexico"
    "Thursday's Widows"
    "DI4RIES"
    "Class Act"
    "Narcos"
    "Man vs Bee"
    "Sexify"
    "13 Reasons Why"
    "Designated Survivor"
    "Surviving Summer"
    "Sex Education"
    "Spy Ops"
    "Selling the OC"
    "Burning Body"
    "Dear Child"
    "Top Boy"
    "Virgin River"
    "Predators"
    "Reporting for Duty"
    "Infamy"
    "Manifest"
    "One Piece"
    "Lupin"
    "Elite"
    "Heart of Invictus"
    "Live to 100: Secrets of the Blue Zones"
    "Lady Voyeur"
    "The Last Kingdom"
    "Vikings: Valhalla"
    "The Sandman"
    "1899"
    "The Ultimatum: Marry or Move On"
    "Wednesday"
    "Who Is Erin Carter"
    "Untold: Swamp Kings"
    "Ozark"
    "The Upshaws"
    "At Home with the Furys"
    "The Chosen One"
    "Dark"
    "The Defenders"
    "Luke Cage"
    "Jessica Jones"
    "Iron Fist"
    "The Punisher"
    "Daredevil"
    "Painkiller"
    "The Night Agent"
    "Stranger Things"
    "The Last Hours of Mario Biondo"
    "How to Become a Cult Leader"
    "A Perfect Story"
    "Sintonia"
    "Sweet Magnolias"
    "Unbreakable Kimmy Schmidt"
    "Survival of the Thickest"
    "Quarterback"
    "Fatal Seduction"
    "The Lincoln Lawyer"
    "Back to 15"
    "Lucifer"
    "From Dusk Till Dawn: The Series"
    "Sleeping Dog"
    "Glamorous"
    "Black Mirror"
    "The Surrogacy"
    "Never Have I Ever"
    "The Witcher"
    "Arnold"
    "Fubar"
    "La casa de papel"
)

# تقسيم الـ titles إلى دفعات
$batchSize = 50
$batches = @()
for ($i = 0; $i -lt $titles.Count; $i += $batchSize) {
    $batch = $titles[$i..([Math]::Min($i + $batchSize - 1, $titles.Count - 1))]
    $batches += , $batch
}

Write-Host "🚀 بدء استيراد $($titles.Count) مسلسل" -ForegroundColor Green
Write-Host "════════════════════════════════════════" -ForegroundColor Yellow
Write-Host "📦 تم تقسيم البيانات إلى $($batches.Count) دفعة" -ForegroundColor Cyan

$totalImported = 0
$totalFailed = 0
$totalSkipped = 0

# استيراد كل دفعة
for ($batchIndex = 0; $batchIndex -lt $batches.Count; $batchIndex++) {
    $batch = $batches[$batchIndex]
    $batchNumber = $batchIndex + 1
    
    Write-Host "`n📤 استيراد الدفعة $batchNumber/$($batches.Count) ($($batch.Count) مسلسل)..." -ForegroundColor Cyan
    
    # إنشاء JSON للطلب
    $titlesJson = $batch | ConvertTo-Json
    $body = @{
        titles = @($batch)
        contentType = "series"
        categorySlug = "foreign-series"
        limit = 1
    } | ConvertTo-Json -Depth 10
    
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:3001/api/admin/import-topcinema" `
            -Method POST `
            -ContentType "application/json" `
            -Body $body `
            -TimeoutSec 120 `
            -ErrorAction Stop
        
        $result = $response.Content | ConvertFrom-Json
        Write-Host "✅ الدفعة $batchNumber: تم بنجاح" -ForegroundColor Green
        Write-Host "   - المستورد: $($result.imported)" -ForegroundColor Green
        Write-Host "   - المكرر: $($result.skipped)" -ForegroundColor Yellow
        Write-Host "   - الأخطاء: $($result.failed)" -ForegroundColor Red
        
        $totalImported += $result.imported
        $totalSkipped += $result.skipped
        $totalFailed += $result.failed
    } catch {
        Write-Host "❌ خطأ في الدفعة $batchNumber: $_" -ForegroundColor Red
        $totalFailed += $batch.Count
    }
    
    # تأخير صغير بين الدفعات
    if ($batchIndex -lt $batches.Count - 1) {
        Start-Sleep -Seconds 2
    }
}

# عرض النتائج النهائية
Write-Host "`n════════════════════════════════════════" -ForegroundColor Yellow
Write-Host "📊 النتائج النهائية" -ForegroundColor Yellow
Write-Host "════════════════════════════════════════" -ForegroundColor Yellow
Write-Host "✅ تم استيراد: $totalImported مسلسل" -ForegroundColor Green
Write-Host "⚠️  تم تخطي (مكرر): $totalSkipped مسلسل" -ForegroundColor Yellow
Write-Host "❌ فشل: $totalFailed مسلسل" -ForegroundColor Red

$successRate = if ($titles.Count -gt 0) { [Math]::Round(($totalImported / $titles.Count) * 100, 2) } else { 0 }
Write-Host "📈 النسبة الناجحة: $successRate%" -ForegroundColor Cyan

Write-Host "`n🎉 انتهى الاستيراج!" -ForegroundColor Green
Write-Host "⏱️  الوقت: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Cyan
